server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: userservice-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: userservice
          __path__: /logs/userservice/appserver.log

  - job_name: hotelservice-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: hotelservice
          __path__: /logs/hotelservice/appserver.log

  - job_name: ratingservice-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: ratingservice
          __path__: /logs/ratingservice/appserver.log

  - job_name: gatewayserver-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: gatewayserver
          __path__: /logs/gatewayserver/appserver.log

  - job_name: rabbitmqproducer-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: rabbitmqproducer
          __path__: /logs/rabbitmqproducer/appserver.log

  - job_name: rabbitmqconsumer-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: rabbitmqconsumer
          __path__: /logs/rabbitmqconsumer/appserver.log

  - job_name: rabbitmqconsumer2-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: rabbitmqconsumer2
          __path__: /logs/rabbitmqconsumer2/appserver.log
