spring:
  application:
    name: RABBIT-CONSUMER
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  config:
    import: configserver:http://localhost:8085  

server:
  port: 9083
